### ISSUE TITLE
External database and legends templates

### ISSUE THREAD

**Issue by flzpenteado** [maciek365/c4-diagrams.net#1]
Just wondering if is a good idea to add a template for external database and legends

**Comment by maciek365** [comment]
I understand that you need grey version of database, right?

Currently you can create grey database using [Copy Style] and [Paste Style] buttons. You can do it in the following way:
1. Select grey External Software System element on your diagram and click [Copy Style] button on the right panel of diagrams.net application.
2. Select blue Data container on your diagram which you want to convert into grey external/existing version and then click [Paste Style] on right panel.
Thats all.

Please notice that official C4 Model approach didn't assume that you need external/existing containers in your C4 diagrams. It assumes that external elements are only on C1 level or landscapes views so there are only external/existing systems or persons - details at Metamodel section: https://c4model.com/
Example landscape diagram with external person and system -> https://c4model.com/img/bigbankplc-SystemLandscape.png

Your question is very helpful. I've just noticed that in EasyC4 there is no External Person. I will add such element into EasyC4. I will also think about adding legends template. Thank you very much for interest of EasyC4 and very useful ideas :-)

**Comment by flzpenteado** [comment]
Cool! Thanks for the feedback!

**Comment by maciek365** [comment]
> 
> 
> Just wondering if is a good idea to add a template for external database and legends

Hi, I've just updated library and currently there are missing elements: External Person and legends - you can use it easily -> https://app.diagrams.net/?clibs=Uhttps://raw.githubusercontent.com/maciek365/c4-diagrams.net/master/EasyC4&splash=0

**Comment by maciek365** [comment]
> 
> 
> Cool! Thanks for the feedback!

Hi, I've just updated library and currently there are missing elements: External Person and legends - you can use it easily -> https://app.diagrams.net/?clibs=Uhttps://raw.githubusercontent.com/maciek365/c4-diagrams.net/master/EasyC4&splash=0
