### ISSUE TITLE
[MacOS] Can't use plugin when using draw.io locally

### ISSUE THREAD

**Issue by gimmebytes** [maciek365/c4-diagrams.net#2]
Hi @maciek365 :-)

I've downloaded the current version of the plugin onto my local hard drive and added the plugin to my locally installed draw.io app.

Draw.io recognizes the plugin, but I can't see the plugin in the toolbox on the left side of the screen and neither I can select the plugin from the the "more shapes..." dialog.

When using your recommended approach, using the web version of draw.io, everything works well but, I would love to use your plugin locally.

I would love to help, if I would know what to change/fix.

Cheers,
Marvin

**System outline**
MBP 16 (2019)
MacOS 10.15.7
Latest version of draw.io installed from [here](https://github.com/jgraph/drawio-desktop/releases)

**Comment by maciek365** [comment]
Thanks for using my plugin. I will try to find out how to run it on local version of draw.io.

**Comment by maciek365** [comment]
>  but I can't see the plugin in the toolbox on the left side of the screen and neither I can select the plugin from the the "more shapes..." dialog.

Hello Marvin,
it seems that you choose the wrong way to open a library in local draw.io application.

You should do it in a way that is described in **_Open a custom shape library_** section on the support page: https://drawio.freshdesk.com/support/solutions/articles/16000067790-how-to-create-and-use-custom-libraries-

So, you should do the following steps if you want to use my plugin locally:
1. Download **c4-diagrams-net-maciek365.xml** file from my plugin repository: https://github.com/maciek365/c4-diagrams.net
2. Start local Draw.io application.
3. Click **_File > Open Library..._** and then select the downloaded file **c4-diagrams-net-maciek365.xml**.

After that steps, you should see the library on the left panel.

I hope that it will help you,
cheers

Maciek

**Comment by gimmebytes** [comment]
Hi @maciek365 !

Thanks a lot! That did the trick :-)

And thanks for the plugin, I think it's the best plugin for draw.io to create C4 diagrams !

Cheers,
Marvin

**Comment by maciek365** [comment]
> 
> 
> Hi @maciek365 !
> 
> Thanks a lot! That did the trick :-)
> 
> And thanks for the plugin, I think it's the best plugin for draw.io to create C4 diagrams !
> 
> Cheers,
> Marvin

I'm very glad that you like it!
Please also check the **newest version** of my plugin available at https://github.com/hycomsa/hycom-c4
There are slightly smaller elements with larger fonts - seems to be more readable in my opinion.
In that version of the plugin, you also can find the new additional type of containers - web browser and mobile application - maybe you like it :-)

I will also try to keep developing this plugin, so please follow this project.

Cheers
Maciek
