### ISSUE TITLE
Possible to add Web Browser and Mobile Application to this library

### ISSUE THREAD

**Issue by dannief** [maciek365/c4-diagrams.net#3]
Noticed that these elements were added to this library: https://github.com/hycomsa/hycom-c4. Possible to add them here as well?

**Comment by maciek365** [comment]
> 
> 
> Noticed that these elements were added to this library: https://github.com/hycomsa/hycom-c4. Possible to add them here as well?

Yes, I will add them soon :-)

**Comment by maciek365** [comment]
I've just added the web browser element you asked for. Feel free to use it :-)

**Comment by dannief** [comment]
Thank You !
