### ISSUE TITLE
[Request] C4 shapes for Lucidchart

### ISSUE THREAD

**Issue by PalaNolho** [maciek365/c4-diagrams.net#4]
Any chance you would be able to provide a version of the shapes that can be used in LucidCharts?

**Comment by maciek365** [comment]
> 
> 
> Any chance you would be able to provide a version of the shapes that can be used in LucidCharts?

Hello, I've just added **_EasyC4-shapes.drawio_** file which you can import in _Lucidchart_ application in the following way:
Please select _File -> Import Diagram -> Draw.io_ and pick downloaded **_EasyC4-shapes.drawio_** file.

I hope that it will help you,
cheers

Maciek

**Comment by PalaNolho** [comment]
so in lucidchart it will only be possible to use the shape and the test will need to be all done and adjusted manually. Is that correct?

**Comment by maciek365** [comment]
> 
> 
> so in lucidchart it will only be possible to use the shape and the test will need to be all done and adjusted manually. Is that correct?

Yes, currently I have no better solution to make the draw.io library fully compatible with the Lucidchart application.
Your request is a great inspiration for me to trying to find/prepare in the future an optimal solution for the Lucidchart app too.
