### ISSUE TITLE
Cannot Resize Elements

### ISSUE THREAD

**Issue by sashokbg** [maciek365/c4-diagrams.net#5]
Hello,

Great library, unfortunately most elements cannot be resized and there situations where they are too big and others were text cannot be shown since they are too small.

Could it be possible to make all elements resizable ?

Best Regards

**Comment by maciek365** [comment]
Hi, I'm glad that you like it :-)
There is a possibility of resizing elements. To do this you should click on the element and then tick the "Resizable" checkbox in the "Format Panel" (on the right side). You can find the "Resizable" checkbox in the Property / Value area. After that you will be able to change the size of the element.

BTW: If the "Format Panel" is not visible then you can show it by clicking one of the icon on the right top.

Regards
Maciek
