### ISSUE TITLE
Mobile app icon

### ISSUE THREAD

**Issue by asindl** [maciek365/c4-diagrams.net#8]
Thanks for the great C4 library for Drawio.
Is there any chance to add a mobile app container symbol as shown here: https://static.structurizr.com/workspace/76749/diagrams/Containers.png

**Comment by maciek365** [comment]
Hi, I'm glad you like my library.
You can find it in the newest version of my plugin available at https://github.com/hycomsa/hycom-c4

**Comment by gonzalezsal** [comment]
Utilizo una solución alternativa. Es una solución tonta, pero funciona bien. Uso un rectángulo redondeado, envío el fondo del contenedor y uso un círculo para simular el botón de un iPad antiguo.
